name: Sync Single File from Upstream

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Download file from Upstream
        run: |
          curl -sLJO https://github.com/Pawdroid/Free-servers/raw/main/sub
          git add sub
          git commit -m "Sync file 'sub' from Upstream"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
