name: Sync Subfolder from Upstream

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.7.0

      - name: Sync subfolder from Upstream
        run: |
          git remote add upstream https://github.com/Pawdroid/Free-servers.git
          git fetch upstream
          git checkout upstream/main sub
          git config --global user.email "bot@github.com"
          git config --global user.name "sync-upstream-bot"
          git add sub
          git commit -m "Sync subfolder from upstream"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
